# fly.toml app configuration file generated for cassino-game-backend on 2025-10-31T13:49:32-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cassino-game-backend'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  HOST = '0.0.0.0'
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '30s'
    method = 'GET'
    path = '/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
