version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: casino-postgres-local
    environment:
      POSTGRES_DB: casino_game
      POSTGRES_USER: casino_user
      POSTGRES_PASSWORD: casino_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U casino_user -d casino_game"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: casino-pgadmin-local
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@casino.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
