"""add_ai_game_fields

Revision ID: 758deb00eae7
Revises: 1c0d42a52479
Create Date: 2026-01-02 13:52:57.420405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758deb00eae7'
down_revision = '1c0d42a52479'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_friendships_status', table_name='friendships')
    op.drop_index('ix_friendships_user1_status', table_name='friendships')
    op.drop_index('ix_friendships_user2_status', table_name='friendships')
    op.drop_index('ix_moderation_reports_created_at', table_name='moderation_reports')
    op.drop_index('ix_moderation_reports_reported_user', table_name='moderation_reports')
    op.drop_index('ix_moderation_reports_status', table_name='moderation_reports')
    op.add_column('players', sa.Column('is_ai', sa.Boolean(), nullable=False))
    op.add_column('rooms', sa.Column('is_ai_game', sa.Boolean(), nullable=False))
    op.add_column('rooms', sa.Column('ai_difficulty', sa.String(length=20), nullable=True))
    op.drop_index('ix_user_blocks_blocked', table_name='user_blocks')
    op.drop_index('ix_user_blocks_blocker', table_name='user_blocks')
    op.drop_index('ix_user_blocks_blocker_blocked', table_name='user_blocks')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_index('ix_users_last_seen', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_last_seen', 'users', ['last_seen'], unique=False)
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_user_blocks_blocker_blocked', 'user_blocks', ['blocker_id', 'blocked_id'], unique=1)
    op.create_index('ix_user_blocks_blocker', 'user_blocks', ['blocker_id'], unique=False)
    op.create_index('ix_user_blocks_blocked', 'user_blocks', ['blocked_id'], unique=False)
    op.drop_column('rooms', 'ai_difficulty')
    op.drop_column('rooms', 'is_ai_game')
    op.drop_column('players', 'is_ai')
    op.create_index('ix_moderation_reports_status', 'moderation_reports', ['status'], unique=False)
    op.create_index('ix_moderation_reports_reported_user', 'moderation_reports', ['reported_user_id'], unique=False)
    op.create_index('ix_moderation_reports_created_at', 'moderation_reports', ['created_at'], unique=False)
    op.create_index('ix_friendships_user2_status', 'friendships', ['user2_id', 'status'], unique=False)
    op.create_index('ix_friendships_user1_status', 'friendships', ['user1_id', 'status'], unique=False)
    op.create_index('ix_friendships_status', 'friendships', ['status'], unique=False)
    # ### end Alembic commands ###
